main: su.nightexpress.excellentenchants.EnchantsPlugin
version: '${project.version}'
name: ExcellentEnchants
author: NightExpress
desciption: Amazing enchantments with seamless integration.
depend: [ nightcore ]
softdepend: [ ProtocolLib, PlaceholderAPI, MythicMobs ]
api-version: 1.19
load: STARTUP