main: su.nightexpress.excellentenchants.ExcellentEnchantsPlugin
version: '${project.version}'
name: ExcellentEnchants
author: NightExpress
desciption: Enchantments that feel like vanilla ones.
depend: [ nightcore ]
softdepend: [ ProtocolLib, NoCheatPlus, PlaceholderAPI, MythicMobs ]
api-version: 1.19
load: STARTUP